name: Workflow one

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go setup  
        uses: actions/setup-go@v5
    
      - name: Build
        run: go build -v ./...
        
      - name: Test with the Go CLI
        run: go test
        
