name: Workflow second

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Chechout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
