name: Workflow caller

on:
  push:
    branches:
      - 'main'

jobs:
  CallingFirstWorkflow:
    uses: tereza-arta/called/.github/workflows/build-run-tests.yml@main

  CallingSecondWorkflow:
    if: ${{ success() }}
    uses: tereza-arta/called/.github/workflows/docker-build-push.yml@main
